Add npmrcPath support
smartlyio/setup-npm-publish-action pull request #362
Opened 2023-03-06 12:08 UTC by fisherking

We have some repos with non-root .npmrc file location. In order to inject auth tokens into files in such repos we need ability to override path to `.npmrc` file

2023-03-06 12:31 UTC, mhalmagiu approved these changes
Looks ok to me

2023-03-07 08:29 UTC, sjagoe requested changes

2023-03-07 08:29 UTC, sjagoe commented on README.md
> +| npmrc_path | no        | Relative path to npmrc file |
```suggestion
| npmrc-path | no        | Relative path to npmrc file |
```

2023-03-07 08:33 UTC, sjagoe approved these changes

2023-03-08 11:27 UTC, merged